language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-api-feed
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed YOUR_DOCKER_HUB/udagram-api-feed:latest
  - cd ../udagram-api-user
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user YOUR_DOCKER_HUB/udagram-api-user:latest
  - cd ../udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend YOUR_DOCKER_HUB/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/udagram-api-feed
  - docker push YOUR_DOCKER_HUB/udagram-api-user
  - docker push YOUR_DOCKER_HUB/udagram-frontend