apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
  labels:
    service: udagram-reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy
    spec:
      containers:
        - name: udagram-reverse-proxy
          image: dai175/udagram-reverse-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

